<!DOCTYPE html>
<html>
<head>
    <title>Pp | Hendrikus</title>
</head>

<body>
    <header>
        <h4>Data Pemantaun Covid19 Wilayah DKI Jakarta
Per 20 April 2022 22:07:23 
HENDRIKUS SUDARSO/191011400802</h3>
    </header>

    <nav>
        <a href="form-daftar.php"> </a>
    </nav>

    <br>

    <table border="1">
    <thead>
        <tr>
            <th>Positif</th>
            <th>dirawat</th>
            <th>sembuh</th>
            <th>meninggal</th>
        </tr>
            <th>1..245.653</th>
            <th>411t</th>
            <th>1.227.793</th>
            <th>15.244</th>
    </thead>
    <tbody>

        <?php
        $sql = "SELECT * FROM calon_siswa";
        $query = mysqli_query($db, $sql);

        while($siswa = mysqli_fetch_array($query)){
            echo "<tr>";

            echo "<td>".$siswa['id']."</td>";
            echo "<td>".$siswa['positif']."</td>";
            echo "<td>".$siswa['dirawat']."</td>";
            echo "<td>".$siswa['meninggal']."</td>";
            echo "<td>".$siswa['agama']."</td>";
            
            echo "<td>";
            echo "<a href='form-edit.php?id=".$siswa['id']."'>Edit</a> | ";
            echo "<a href='hapus.php?id=".$siswa['id']."'>Hapus</a>";
            echo "</td>";

            echo "</tr>";
        }
        ?>

    </tbody>
    </table>

    <p>Total: <?php echo mysqli_num_rows($query) ?></p>

    </body>
</html>